# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'GuiadoValeMaster' do

pod 'Firebase', '>= 2.5.0'

end

target 'GuiadoValeMasterTests' do

end

target 'GuiadoValeMasterUITests' do

end

